# Molecules representations

This notebook tests different representations of molecules. The autoML framework Pycaret is used to quickly test classical machine learning models.

This code is made to be run locally within current repository. If you work in Google Colab, adjust the path to the `processed_df.csv` and `df_fp.csv` file accordingly and install the libraries provided in the requirements.

In [3]:
import pandas as pd
import numpy as np

import pycaret
from pycaret.regression import *

from sklearn.model_selection import cross_val_score, KFold
from sklearn.svm import SVR

## Extended-connectivity fingerprints (ECFPs)

Fingerprints uploads are given in the `Data_processing.ipynb` notebook. Here we use the ready-made file `df_fp.csv`.

In [27]:
df = pd.read_csv('/content/drive/MyDrive/статья/Data/df_fp.csv')

### Model comprasion

In [28]:
df = df.drop('Smiles', axis =1)

In [ ]:
# init the class
exp = RegressionExperiment()

In [ ]:
# check the type of exp
type(exp)

pycaret.regression.oop.RegressionExperiment

In [ ]:
# init setup on exp
exp.setup(df, target = 'pIC50', session_id = 1)

In [ ]:
# compare baseline models
exp.compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

LGBMRegressor(n_jobs=-1, random_state=1)

In [29]:
X = df.drop(['pIC50'], axis=1)
y = df['pIC50']

In [31]:
model = SVR()

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

scores_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2')

print(f"MSE: {np.mean(scores):.2f} +/- {np.std(scores):.2f}")
print(f"Mean R2: {np.mean(scores_r2):.2f} +/- {np.std(scores_r2):.2f}")

MSE: -0.34 +/- 0.01
Mean R2: 0.72 +/- 0.01


## Mol2vec

### Descriptor loading

In [ ]:
%pip install git+https://github.com/samoturk/mol2vec

In [ ]:
import sys, os

sys.path.append(os.path.dirname(os.path.dirname(os.getcwd()))+'/mol2vec')

from rdkit import Chem
from rdkit.Chem import PandasTools
from rdkit.Chem.Draw import IPythonConsole
from rdkit.Chem import Draw

from mol2vec.features import mol2alt_sentence, mol2sentence, MolSentence, DfVec, sentences2vec
from gensim.models import word2vec

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/статья/Data/processed_df.csv')

In [ ]:
df = df.drop('IC50', axis=1)

In [ ]:
model = word2vec.Word2Vec.load('/content/drive/MyDrive/статья/Representations/model_300dim.pkl')

In [ ]:
df_mol2 = df

df_mol2['ROMol'] = df_mol2['Smiles'].apply(lambda x: Chem.MolFromSmiles(x))

In [ ]:
df_mol2

,Smiles,pIC50,ROMol
0,Cc1cc(Nc2cc(C(F)(F)F)ccn2)nc(-c2cnc([C@@]3(O)C...,8.560667,<rdkit.Chem.rdchem.Mol object at 0x7d8e2b6b6ce0>
1,Cc1ncc(-c2cn3ccnc3c(Nc3ccc(N4CCN(C5COC5)CC4)cc...,8.207608,<rdkit.Chem.rdchem.Mol object at 0x7d8e2b6b6b20>
2,c1ccc(COc2cccc(Nc3nccc(-c4nccs4)n3)c2)cc1,6.301030,<rdkit.Chem.rdchem.Mol object at 0x7d8e2b6b6d50>
3,c1cncc(Oc2cccc(Nc3nccc(-c4nccs4)n3)c2)c1,6.301030,<rdkit.Chem.rdchem.Mol object at 0x7d8e2b6b6dc0>
4,Cc1cc(Nc2nn(-c3ccc(C(F)(F)F)cc3)c(=O)c3ccccc23...,6.279841,<rdkit.Chem.rdchem.Mol object at 0x7d8e2b6b6e30>
...,...,...,...
3171,CC(C)Cn1cnc(-c2ccnc(Nc3cc(Cl)c4[nH]c(C(=O)N(C)...,6.917574,<rdkit.Chem.rdchem.Mol object at 0x7d8e29daa6c0>
3172,CN1CCC(NC(=O)c2cc3cc(Nc4nccc(-c5cn(C)cn5)n4)cc...,8.244125,<rdkit.Chem.rdchem.Mol object at 0x7d8e29daa730>
3173,Cc1ccc(-c2cnc([C@@]3(O)CC[C@H](C(=O)O)C(C)(C)C...,9.045757,<rdkit.Chem.rdchem.Mol object at 0x7d8e29daa7a0>
3174,NCCCNc2nc(c1cccc(F)c1)cc3ncccc23,6.071000,<rdkit.Chem.rdchem.Mol object at 0x7d8e29daa810>
3175,NCCCNc2nc(c1cccc(Cl)c1)cc3ncccc23,6.585000,<rdkit.Chem.rdchem.Mol object at 0x7d8e29daa880>

In [ ]:
df_mol2 ['sentence'] = df_mol2.apply(lambda x: MolSentence(mol2alt_sentence(x['ROMol'], 1)), axis=1)

In [ ]:
vectors = [np.mean([model.wv[word] for word in sentence if word in model.wv], axis=0) for sentence in df_mol2['sentence']]
df_mol2['mol2vec'] = vectors

In [ ]:
df_mol2.columns

Index(['Smiles', 'pIC50', 'ROMol', 'sentence', 'mol2vec'], dtype='object')

In [ ]:
new_mol2vec = np.vstack(df_mol2['mol2vec'].values)
new_mol2vec_columns = [f'2vec_{i}' for i in range(new_mol2vec.shape[1])]
new_mol2vec_df = pd.DataFrame(new_mol2vec, columns=new_mol2vec_columns)

df_mol2vec = pd.concat([df_mol2, new_mol2vec_df], axis=1)

df_mol2vec = df_mol2vec.drop(['ROMol', 'sentence', 'mol2vec'], axis=1)

In [ ]:
df_mol2vec

,Smiles,pIC50,2vec_0,2vec_1,2vec_2,2vec_3,2vec_4,2vec_5,2vec_6,2vec_7,...,2vec_290,2vec_291,2vec_292,2vec_293,2vec_294,2vec_295,2vec_296,2vec_297,2vec_298,2vec_299
0,Cc1cc(Nc2cc(C(F)(F)F)ccn2)nc(-c2cnc([C@@]3(O)C...,8.560667,0.064856,-0.044210,-0.041089,0.133609,-0.031914,-0.018043,-0.237680,0.020456,...,-0.019264,0.208332,0.213050,-0.018601,-0.172787,-0.085745,-0.085349,-0.077389,-0.231701,-0.015070
1,Cc1ncc(-c2cn3ccnc3c(Nc3ccc(N4CCN(C5COC5)CC4)cc...,8.207608,0.119973,-0.148029,-0.045540,0.165872,-0.006626,0.031583,-0.232965,0.011170,...,-0.014664,0.226500,0.172681,-0.072645,-0.185177,-0.050050,-0.122895,-0.030302,-0.226732,-0.033468
2,c1ccc(COc2cccc(Nc3nccc(-c4nccs4)n3)c2)cc1,6.301030,0.024893,-0.083418,-0.045309,0.214921,0.006840,0.032333,-0.241734,-0.022715,...,-0.025218,0.217300,0.244201,-0.037445,-0.117619,-0.057086,-0.078120,-0.049323,-0.210054,-0.028590
3,c1cncc(Oc2cccc(Nc3nccc(-c4nccs4)n3)c2)c1,6.301030,0.050926,-0.099858,-0.052455,0.206724,0.016108,0.032634,-0.231796,-0.017200,...,-0.017454,0.221582,0.254183,-0.044519,-0.114452,-0.054392,-0.087771,-0.046296,-0.227397,-0.020916
4,Cc1cc(Nc2nn(-c3ccc(C(F)(F)F)cc3)c(=O)c3ccccc23...,6.279841,0.081359,-0.079856,-0.076063,0.172600,-0.029412,-0.010877,-0.235642,-0.007948,...,-0.034362,0.187266,0.239657,-0.023037,-0.127927,-0.036033,-0.048713,-0.061949,-0.242218,-0.011565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,CC(C)Cn1cnc(-c2ccnc(Nc3cc(Cl)c4[nH]c(C(=O)N(C)...,6.917574,0.071768,-0.071396,-0.070719,0.118958,0.028896,0.055135,-0.194803,-0.021354,...,-0.003704,0.185389,0.249137,-0.032117,-0.122750,-0.067457,-0.088323,-0.074768,-0.260363,-0.048995
3172,CN1CCC(NC(=O)c2cc3cc(Nc4nccc(-c5cn(C)cn5)n4)cc...,8.244125,0.090950,-0.107925,-0.045017,0.140513,-0.021046,0.011915,-0.201466,-0.005737,...,-0.001768,0.228375,0.217691,-0.072904,-0.146535,-0.069524,-0.122901,-0.066617,-0.246668,-0.029879
3173,Cc1ccc(-c2cnc([C@@]3(O)CC[C@H](C(=O)O)C(C)(C)C...,9.045757,0.032028,-0.053478,-0.044626,0.084859,-0.024854,-0.046218,-0.228670,0.039847,...,-0.010045,0.213080,0.181817,-0.026956,-0.151518,-0.105240,-0.089057,-0.068845,-0.236272,0.012547
3174,NCCCNc2nc(c1cccc(F)c1)cc3ncccc23,6.071000,0.062937,-0.073034,-0.034268,0.182084,0.022170,0.044227,-0.256021,-0.010875,...,-0.027092,0.195613,0.257108,-0.001273,-0.151096,-0.063691,-0.065793,-0.098782,-0.230826,-0.044452
3175,NCCCNc2nc(c1cccc(Cl)c1)cc3ncccc23,6.585000,0.052488,-0.079458,-0.030203,0.180255,0.029183,0.058331,-0.236658,-0.007113,...,-0.030425,0.203109,0.269509,-0.002286,-0.141434,-0.050917,-0.066578,-0.076181,-0.217607,-0.053680

In [ ]:
df_mol2vec.to_csv('/content/drive/MyDrive/статья/Representations/mol2vec_df.csv', index = False)

### Model comprasion

In [ ]:
df_mol2vec = df_mol2vec.drop('Smiles', axis =1)

In [ ]:
exp = RegressionExperiment()

In [ ]:
exp.setup(df_mol2vec, target = 'pIC50', session_id = 1)

In [ ]:
exp.compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

LGBMRegressor(n_jobs=-1, random_state=1)

In [ ]:
df_mol2vec

,Smiles,pIC50,2vec_0,2vec_1,2vec_2,2vec_3,2vec_4,2vec_5,2vec_6,2vec_7,...,2vec_290,2vec_291,2vec_292,2vec_293,2vec_294,2vec_295,2vec_296,2vec_297,2vec_298,2vec_299
0,Cc1cc(Nc2cc(C(F)(F)F)ccn2)nc(-c2cnc([C@@]3(O)C...,8.560667,0.064856,-0.044210,-0.041089,0.133609,-0.031914,-0.018043,-0.237680,0.020456,...,-0.019264,0.208332,0.213050,-0.018601,-0.172787,-0.085745,-0.085349,-0.077389,-0.231701,-0.015070
1,Cc1ncc(-c2cn3ccnc3c(Nc3ccc(N4CCN(C5COC5)CC4)cc...,8.207608,0.119973,-0.148029,-0.045540,0.165872,-0.006626,0.031583,-0.232965,0.011170,...,-0.014664,0.226500,0.172681,-0.072645,-0.185177,-0.050050,-0.122895,-0.030302,-0.226732,-0.033468
2,c1ccc(COc2cccc(Nc3nccc(-c4nccs4)n3)c2)cc1,6.301030,0.024893,-0.083418,-0.045309,0.214921,0.006840,0.032333,-0.241734,-0.022715,...,-0.025218,0.217300,0.244201,-0.037445,-0.117619,-0.057086,-0.078120,-0.049323,-0.210054,-0.028590
3,c1cncc(Oc2cccc(Nc3nccc(-c4nccs4)n3)c2)c1,6.301030,0.050926,-0.099858,-0.052455,0.206724,0.016108,0.032634,-0.231796,-0.017200,...,-0.017454,0.221582,0.254183,-0.044519,-0.114452,-0.054392,-0.087771,-0.046296,-0.227397,-0.020916
4,Cc1cc(Nc2nn(-c3ccc(C(F)(F)F)cc3)c(=O)c3ccccc23...,6.279841,0.081359,-0.079856,-0.076063,0.172600,-0.029412,-0.010877,-0.235642,-0.007948,...,-0.034362,0.187266,0.239657,-0.023037,-0.127927,-0.036033,-0.048713,-0.061949,-0.242218,-0.011565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,CC(C)Cn1cnc(-c2ccnc(Nc3cc(Cl)c4[nH]c(C(=O)N(C)...,6.917574,0.071768,-0.071396,-0.070719,0.118958,0.028896,0.055135,-0.194803,-0.021354,...,-0.003704,0.185389,0.249137,-0.032117,-0.122750,-0.067457,-0.088323,-0.074768,-0.260363,-0.048995
3172,CN1CCC(NC(=O)c2cc3cc(Nc4nccc(-c5cn(C)cn5)n4)cc...,8.244125,0.090950,-0.107925,-0.045017,0.140513,-0.021046,0.011915,-0.201466,-0.005737,...,-0.001768,0.228375,0.217691,-0.072904,-0.146535,-0.069524,-0.122901,-0.066617,-0.246668,-0.029879
3173,Cc1ccc(-c2cnc([C@@]3(O)CC[C@H](C(=O)O)C(C)(C)C...,9.045757,0.032028,-0.053478,-0.044626,0.084859,-0.024854,-0.046218,-0.228670,0.039847,...,-0.010045,0.213080,0.181817,-0.026956,-0.151518,-0.105240,-0.089057,-0.068845,-0.236272,0.012547
3174,NCCCNc2nc(c1cccc(F)c1)cc3ncccc23,6.071000,0.062937,-0.073034,-0.034268,0.182084,0.022170,0.044227,-0.256021,-0.010875,...,-0.027092,0.195613,0.257108,-0.001273,-0.151096,-0.063691,-0.065793,-0.098782,-0.230826,-0.044452
3175,NCCCNc2nc(c1cccc(Cl)c1)cc3ncccc23,6.585000,0.052488,-0.079458,-0.030203,0.180255,0.029183,0.058331,-0.236658,-0.007113,...,-0.030425,0.203109,0.269509,-0.002286,-0.141434,-0.050917,-0.066578,-0.076181,-0.217607,-0.053680

In [ ]:
X = df_mol2vec.drop(['Smiles', 'pIC50'], axis=1)
y = df_mol2vec['pIC50']

In [ ]:
model = SVR()

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

In [ ]:
scores_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2')

In [ ]:
print(f"MSE: {np.mean(scores):.2f} +/- {np.std(scores):.2f}")
print(f"Среднее R2: {np.mean(scores_r2):.2f} +/- {np.std(scores_r2):.2f}")

MSE: -0.66 +/- 0.03
Среднее R2: 0.47 +/- 0.02

## MACCS fingerprints

In [ ]:
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import MACCSkeys

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/статья/Data/processed_df.csv')

### Descriptor loading

In [ ]:
def get_maccs_fp(smiles):
    mol = Chem.MolFromSmiles(smiles)
    if mol is not None:
        return MACCSkeys.GenMACCSKeys(mol)
    return None

In [ ]:
df['MACCS_FP'] = df['Smiles'].apply(get_maccs_fp)

df['MACCS_FP_BitString'] = df['MACCS_FP'].apply(lambda x: x.ToBitString() if x is not None else None)

In [ ]:
fp_df = df['MACCS_FP_BitString'].str.split('', expand=True).iloc[:, 1:-1]

df_MACCS = pd.concat([df, fp_df], axis=1)

df_MACCS = df_MACCS.drop(['MACCS_FP', 'MACCS_FP_BitString'], axis=1)

In [ ]:
df_MACCS = df_MACCS.drop(['IC50'], axis = 1)

In [ ]:
df_MACCS.to_csv('/content/drive/MyDrive/статья/Representations/MACCS_df.csv', index=False)

### Model comprasion

In [ ]:
df_MACCS = df_MACCS.drop('Smiles', axis =1)

In [ ]:
# init the class
exp = RegressionExperiment()

In [ ]:
# init setup on exp
exp.setup(df_MACCS, target = 'pIC50', session_id = 1)

In [ ]:
# compare baseline models
exp.compare_models()

LGBMRegressor(n_jobs=-1, random_state=1)

In [ ]:
X = df_MACCS.drop(['Smiles', 'pIC50'], axis=1)
y = df_MACCS['pIC50']

In [ ]:
model = SVR()

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

In [ ]:
scores_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2')

In [ ]:
print(f"MSE: {np.mean(scores):.2f} +/- {np.std(scores):.2f}")
print(f"Среднее R2: {np.mean(scores_r2):.2f} +/- {np.std(scores_r2):.2f}")

MSE: -0.49 +/- 0.02
Среднее R2: 0.60 +/- 0.01

## MinHashed Atom Pair (MAP4)

In [ ]:
from map4 import MAP4
import pandas as pd
from rdkit import Chem
from rdkit.Chem import AllChem
import numpy as np

### Descriptor loading

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/статья/Data/processed_df.csv')

In [ ]:
map4 = MAP4(
    dimensions=2048,
    radius=2,
    include_duplicated_shingles=False,
)

In [ ]:
# Function for calculating the MAP4 fingerprint
def calculate_map4(smiles):
    mol = Chem.MolFromSmiles(smiles)
    return map4.calculate(mol)

In [ ]:
fingerprints = df['Smiles'].apply(calculate_map4)

MAP4_fingerprints = pd.DataFrame(fingerprints.tolist(), index=df.index)
MAP4_fingerprints.columns = [f'MAP4_{i}' for i in range(2048)]

df_MAP4 = pd.concat([df, MAP4_fingerprints], axis=1)

In [ ]:
df_MAP4

,Smiles,IC50,pIC50,MAP4_0,MAP4_1,MAP4_2,MAP4_3,MAP4_4,MAP4_5,MAP4_6,...,MAP4_2038,MAP4_2039,MAP4_2040,MAP4_2041,MAP4_2042,MAP4_2043,MAP4_2044,MAP4_2045,MAP4_2046,MAP4_2047
0,Cc1cc(Nc2cc(C(F)(F)F)ccn2)nc(-c2cnc([C@@]3(O)C...,2.750000,8.560667,0,1,1,1,1,0,0,...,0,1,0,1,0,1,1,0,1,0
1,Cc1ncc(-c2cn3ccnc3c(Nc3ccc(N4CCN(C5COC5)CC4)cc...,6.200000,8.207608,1,0,0,0,0,0,0,...,1,0,1,1,0,0,0,0,0,0
2,c1ccc(COc2cccc(Nc3nccc(-c4nccs4)n3)c2)cc1,500.000000,6.301030,1,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
3,c1cncc(Oc2cccc(Nc3nccc(-c4nccs4)n3)c2)c1,500.000000,6.301030,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Cc1cc(Nc2nn(-c3ccc(C(F)(F)F)cc3)c(=O)c3ccccc23...,525.000000,6.279841,0,0,0,1,1,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3171,CC(C)Cn1cnc(-c2ccnc(Nc3cc(Cl)c4[nH]c(C(=O)N(C)...,120.900000,6.917574,0,0,1,1,0,1,0,...,0,0,0,0,1,1,0,0,0,0
3172,CN1CCC(NC(=O)c2cc3cc(Nc4nccc(-c5cn(C)cn5)n4)cc...,5.700000,8.244125,0,0,1,0,0,1,0,...,0,0,0,0,0,1,0,0,0,0
3173,Cc1ccc(-c2cnc([C@@]3(O)CC[C@H](C(=O)O)C(C)(C)C...,0.900000,9.045757,0,0,0,0,0,1,0,...,0,1,0,0,0,1,0,0,0,1
3174,NCCCNc2nc(c1cccc(F)c1)cc3ncccc23,849.180475,6.071000,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
3175,NCCCNc2nc(c1cccc(Cl)c1)cc3ncccc23,260.015956,6.585000,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [ ]:
df_MAP4.to_csv('/content/drive/MyDrive/статья/Representations/MAP4_df.csv', index=False)

### Model comprasion

In [ ]:
import pycaret
from pycaret.regression import *

In [ ]:
# init the class
exp = RegressionExperiment()

In [ ]:
df_MAP4 = df_MAP4.drop(['Smiles', 'IC50'], axis =1)

In [ ]:
# init setup on exp
exp.setup(df_MAP4, target='pIC50', session_id=1,
          fold=5)

In [ ]:
# compare baseline models
exp.compare_models()

LGBMRegressor(n_jobs=-1, random_state=1)

In [ ]:
X = df_MAP4.drop(['Smiles', 'pIC50', 'IC50'], axis=1)
y = df_MAP4['pIC50']

In [ ]:
model = SVR()

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

scores_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2')

print(f"MSE: {np.mean(scores):.2f} +/- {np.std(scores):.2f}")
print(f"Среднее R2: {np.mean(scores_r2):.2f} +/- {np.std(scores_r2):.2f}")

MSE: -0.38 +/- 0.02
Среднее R2: 0.69 +/- 0.01

## PubChem fingerprints

### Descriptor loading

In [ ]:
pip install pubchempy

In [ ]:
import deepchem as dc

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/статья/Data/processed_df.csv')

In [ ]:
featurizer = dc.feat.PubChemFingerprint()
features = featurizer.featurize(df['Smiles'])

In [ ]:
fp_df = pd.DataFrame(features)

In [ ]:
def convert_to_array(array_str):
  if isinstance(array_str, str):
    return np.array(ast.literl_eval(array_str.replace('\n', '')))
  return array_str

In [ ]:
fp_df[0] = fp_df[0].apply(convert_to_array)

In [ ]:
features_df = pd.DataFrame(fp_df[0].tolist(), index=fp_df.index)
features_df.columns = [f'fp_{i+1}' for i in range(features_df.shape[1])]

In [ ]:
df_pubchem = pd.concat([df, features_df], axia = 1)

In [ ]:
df_pubchem.to_csv('/content/drive/MyDrive/статья/df_pubchem.csv', index = False)

### Model comprasion

In [20]:
df_pubchem = pd.read_csv('/content/drive/MyDrive/статья/df_pubchem.csv')

In [5]:
# init the class
exp = RegressionExperiment()

In [21]:
df_pubchem = df_pubchem.drop(['Smiles', 'IC50'], axis =1)

In [8]:
# init setup on exp
exp.setup(df_pubchem, target='pIC50', session_id=1,
          fold=5)

In [9]:
# compare baseline models
exp.compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

LGBMRegressor(n_jobs=-1, random_state=1)

In [22]:
indices_to_remove = [2778, 2779, 2780, 2781, 2784, 2785, 2842, 2853, 2906, 2908, 2909, 2910]
df_pubchem = df_pubchem.drop(indices_to_remove, axis=0, errors='ignore')

In [23]:
X = df_pubchem.drop(['pIC50'], axis=1)
y = df_pubchem['pIC50']

In [26]:
model = SVR()

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, X, y, cv=kf, scoring='neg_mean_squared_error')

scores_r2 = cross_val_score(model, X, y, cv=kf, scoring='r2')

print(f"MSE: {np.mean(scores):.2f} +/- {np.std(scores):.2f}")
print(f"Mean R2: {np.mean(scores_r2):.2f} +/- {np.std(scores_r2):.2f}")

MSE: -0.47 +/- 0.04
Среднее R2: 0.62 +/- 0.02